language: ruby
services:
  - postgresql
rvm:
  - 2.3.1
env:
  global:
    - APP_SECRET_TOKEN=b2724973fd81c2f4ac0f92ac48eb3f0152c4a11824c122bcf783419a4c51d8b9bba81c8ba6a66c7de599677c7f486242cf819775c433908e77c739c5c8ae118d
    - DATABASE_ADAPTER=postgresql
    - DATABASE_USERNAME=postgres
cache: bundler
script:
  - bundle exec rake
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rake update; fi
